/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FoundRouteImport } from './routes/found'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LostRouteImport } from './routes/lost'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as AuthenticatedReportNewRouteImport } from './routes/_authenticated/report.new'
import { Route as AuthenticatedChatReportIdUserIdRouteImport } from './routes/_authenticated/chat.$reportId.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportNewRoute = AuthenticatedReportNewRouteImport.update({
  id: '/report/new',
  path: '/report/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatReportIdUserIdRoute =
  AuthenticatedChatReportIdUserIdRouteImport.update({
    id: '/chat/$reportId/$userId',
    path: '/chat/$reportId/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/found': typeof FoundRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report/$id': typeof ReportIdRoute
  '/report/new': typeof AuthenticatedReportNewRoute
  '/chat/$reportId/$userId': typeof AuthenticatedChatReportIdUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/found': typeof FoundRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report/$id': typeof ReportIdRoute
  '/report/new': typeof AuthenticatedReportNewRoute
  '/chat/$reportId/$userId': typeof AuthenticatedChatReportIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/found': typeof FoundRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lost': typeof LostRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/report/$id': typeof ReportIdRoute
  '/_authenticated/report/new': typeof AuthenticatedReportNewRoute
  '/_authenticated/chat/$reportId/$userId': typeof AuthenticatedChatReportIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/found'
    | '/how-it-works'
    | '/lost'
    | '/map'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/report/$id'
    | '/report/new'
    | '/chat/$reportId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/found'
    | '/how-it-works'
    | '/lost'
    | '/map'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/report/$id'
    | '/report/new'
    | '/chat/$reportId/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/found'
    | '/how-it-works'
    | '/lost'
    | '/map'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/report/$id'
    | '/_authenticated/report/new'
    | '/_authenticated/chat/$reportId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FoundRoute: typeof FoundRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LostRoute: typeof LostRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/new': {
      id: '/_authenticated/report/new'
      path: '/report/new'
      fullPath: '/report/new'
      preLoaderRoute: typeof AuthenticatedReportNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$reportId/$userId': {
      id: '/_authenticated/chat/$reportId/$userId'
      path: '/chat/$reportId/$userId'
      fullPath: '/chat/$reportId/$userId'
      preLoaderRoute: typeof AuthenticatedChatReportIdUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportNewRoute: typeof AuthenticatedReportNewRoute
  AuthenticatedChatReportIdUserIdRoute: typeof AuthenticatedChatReportIdUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportNewRoute: AuthenticatedReportNewRoute,
  AuthenticatedChatReportIdUserIdRoute: AuthenticatedChatReportIdUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FoundRoute: FoundRoute,
  HowItWorksRoute: HowItWorksRoute,
  LostRoute: LostRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
